[package]
name = "rusty-bank"
version = "0.1.0"
authors = ["Oliver Gavin"]
edition = "2021"

[dependencies]
anyhow = "1.0.57"
env_logger = "0.9.0"
log = "0.4.14"

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"
tempfile = "3.3.0"
